language: node_js
node_js:
- '4.0'
- '9.0'
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: CvTkhw69zzT9topsMq5pbYSWXZsOHXE/koTIDprpaU2DeLc6TSQYvnFfBW+iR5YAv395v3T5jdkt02Re4wxF9Vt9v2jtgbzFZiTZmyoPxHjdCqWd5WBDdqHZ9ksT0+rO9+i8Q7fKaLBcH9YgJwbpEhR6kQGzOcD817MnJL/EKcyjyxk3EN/TU587JnV5ivTgx904+4d9DXVyozihQDlAMbjz+JQAquWO3UETUjBJBUvSAlkJqvyTXoN7CiacejYfBoq7isB6awON0oHnuZRVMVudkGa3h79/3I/VeDEXMiG7mvvDMl2Jh7jXx63vcXSh/bugJrOM1xFDkJzUbvXr0QY3LsI+c/HAONyO3Def5wVpNrHmRVOzzKAvpHqLwh1vZeBIJJaAeJUQ9d/m32nETbR6dT+AQ/Fjmq4pkzs9+Df7q+TtAD2Kcl1PgWobX8jV2ahYq5+otvb5bPwoHEMN6Y5xr/X/BqKboITLL8fCVGZNL4IpfBHhwniUjGmUQgXKCBu13p90OmR5POMG11S6uN+RGhv5FTWF6IvqZRHimzjlsqvrBlXQmvnHBjqymXgCa3LnLmQk4sHJLfuQp2IVPTxIxh3P8jxFxqvfTCP84U51Yeuw4rv44QhdsNI2gLKcSbddRgDBbD8vE8fnSgN6gy/x+aTgn+qnO499jSWZ7II=
  file:
    - "rehype-slug.js"
    - "rehype-slug.min.js"
  on:
    tags: true
    node: '9.0'
