language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: eHgkXrr7mfyiGK2R3Qk+y87LLFneWrlIM7kyUaAcawzfB3umd+KO/5zHRCVjYGDguxHvSd4YCD2KFqsT+5HUuM3beujGa5hAtUOJTRy5mMBcU0D6tuXMbiVhKdcXn7AOkXQi0XRyriWh1a2x/KNA6YmpQD9OqhXQl3kqvq59Btey5f8BDJRSIaVOG+lqPsIATeT//mka4ouw1bne3OLtbsGz3n+VM5VJ3MDq1DVV83DL5jQ3Tv6glVDP9W18EzD0IwD/yQy6/lVkUcS5kNl/Nh3ex29idY7I0i6ic+NqjM5BcHPRC1adJTxdWeOh9dW1UgmuapVMoQM6Y0Sr251Zr1x3O+hcpCzbD0YwcEzQPEHmTMuvGW24L2h4gWoZgnvCSPnhsOxvQFyF0/zQZxHZtNHa5EOJ+J4Pdvvj6mZ+QsmqHnwF6Khr0wPZNVyVP62/dafDdSSFrOMLd3cc/limg24yVN22HiFO5GMv6A8d2q39aRIdE8sll3a9qBG6B8GQxSG1YLtp3IDH6de5hQ4fDjExYkNoLdcUGdKbc3SoMYUMWGKvSCbWYVZPEDaPLQk93lrEsrg7UUx/78GiUibFQKQPTd6cL6nz7pHFCKY4kcZ28VaTfj5sMB5KH5Ga9Jn9XMB8yCYGWE46NGysNetpXVk3TAyfYtmcEao1SrHuxZI=
  file:
    - 'rehype-slug.js'
    - 'rehype-slug.min.js'
  on:
    tags: true
